name: sync_with_meilisearch
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.0.0  # For making HTTP requests
  dotenv: ^4.1.0 
  meilisearch: ^0.15.0
  dart_appwrite: ^8.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
